CREATE TABLE IF NOT EXISTS yearly_opponent_per_game_stats (
    id VARCHAR(14) PRIMARY KEY,
    player TEXT NOT NULL,
    mp FLOAT NOT NULL, 
    fg FLOAT NOT NULL, 
    fga FLOAT NOT NULL, 
    fg_pct FLOAT NOT NULL, 
    fg3 FLOAT NOT NULL, 
    fg3a FLOAT NOT NULL, 
    fg3_pct FLOAT NOT NULL,
    fg2 FLOAT NOT NULL, 
    fg2a FLOAT NOT NULL, 
    fg2_pct FLOAT NOT NULL, 
    ft FLOAT NOT NULL, 
    fta FLOAT NOT NULL, 
    ft_pct FLOAT NOT NULL, 
    orb FLOAT NOT NULL, 
    drb FLOAT NOT NULL, 
    trb FLOAT NOT NULL,
    ast FLOAT NOT NULL, 
    stl FLOAT NOT NULL, 
    blk FLOAT NOT NULL, 
    tov FLOAT NOT NULL, 
    pf FLOAT NOT NULL, 
    pts FLOAT NOT NULL, 
    team TEXT NOT NULL, 
    year INT NOT NULL
);